apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvp-3.0-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mvp-3.0-app
  template:
    metadata:
      labels:
        app: mvp-3.0-app
    spec:
      containers:
      - name: mvp-3.0-app
        image: acrdvmvpem01acrgwc01.azurecr.io/mvp-3.0:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
