name: Terraform

on:
  push:
    branches:
      - 'master'
      - 'feature/**'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'terraform/modules/network/'
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -var-file=non-pd.tfvars
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=non-pd.tfvars
