name: Terraform Deployment

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev, qa, prod)"
        required: true
        default: "dev"
      application_instance:
        description: "Application instance (e.g., em01, em02)"
        required: true
        default: "em01"

permissions:
  contents: read
  id-token: write

jobs:
  deploy_network:
    uses: ./.github/workflows/network.yaml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      application_instance: ${{ github.event.inputs.application_instance || 'em01' }}
      #require_apply_approval: ${{ github.event.inputs.require_apply_approval || 'false' }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  deploy_kubernetes:
    needs: deploy_network
    uses: ./.github/workflows/kubernetes.yaml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      application_instance: ${{ github.event.inputs.application_instance || 'em01' }}
      #require_apply_approval: ${{ github.event.inputs.require_apply_approval || 'false' }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  deploy_sql:
    needs: deploy_network
    uses: ./.github/workflows/sql.yaml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      application_instance: ${{ github.event.inputs.application_instance || 'em01' }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
